name: 'Test AWS Access'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::216608711744:role/sts-lab-2-target
          role-session-name: OIDCSession

      - name: Retrieve AWS Secret
        run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2 --query SecretString --output text
        shell: bash
